/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        normal: '#aaaa99',
        fire: '#ff4422',
        water: '#3399ff',
        electric: '#ffcc33',
        grass: '#77cc55',
        ice: '#96D9D6',
        fighting: '#bb5544',
        poison: '#aa5599',
        ground: '#ddbb55',
        flying: '#8899ff',
        psychic: '#ff5599',
        bug: '#aabb22',
        rock: '#bbaa66',
        ghost: '#6666bb',
        dragon: '#7766ee',
        dark: '#775544',
        steel: '#aaaabb',
        fairy: '#ee99ee',
        'sky-blue': '#d2e1f2',
        'dark-light-blue': '#ACC8E5',
        hp: '#ff5959',
        'hp-inner': '#ff0000',
        'hp-border': '#b70000',
        attack: '#f5ac78',
        'attack-inner': '#f08030',
        'attack-border': '#ad5d24',
        defense: '#fae078',
        'defense-inner': '#f8d030',
        'defense-border': '#c3a83a',
        'special-attack': '#9db7f5',
        'special-attack-inner': '#6890f0',
        'special-attack-border': '#6d88c9',
        'special-defense': '#a7db8d',
        'special-defense-inner': '#78c850',
        'special-defense-border': '#6ba24f',
        speed: '#fa92b2',
        'speed-inner': '#f85888',
        'speed-border': '#d74c76',
      },
      backgroundImage: {
        'poke-bg': 'url(../src/assets/poke-bg.png)',
      },
    },
  },
  safelist: [
    {
      pattern: /(bg|text|border)-./,
    },
  ],
  plugins: [],
};
